export const LOG_REDACTION_PATHS = [
  'req.headers.authorization',
  'req.headers.cookie',
  'password',
  'DATABASE_URL',
  'req.body.refreshToken',
  'req.body.identityToken',
  'req.body.rawNonce',
  'refreshToken',
  'accessToken',
  'refreshTokenHash',
  'identityToken',
  'rawNonce',
  'authorizationCode',
  'providerCredential',
  'providerSubject',
  'email',
  'verifiedProviderPayload',
  'JWT_ACCESS_SECRET',
  'JWT_REFRESH_SECRET',
] as const;
